### ISSUE TITLE
Feedback Aufgabe 3

### ISSUE THREAD

**Issue by AnnaLotz** [LucasMaurice92/EIA2#1]
- Skizze, Use-Cases und AD's in eine Datei!
- AD zu ungenau und so zu nichtssagend

Anwendung funktioniert einwandfrei

**Comment by Plagiatus** [comment]
Wenn das Konzept nicht in einer Datei ist, gilt es ab sofort als falsch abgegeben, das ist aber eigentlich bekannt!  
Erros in der Konsole wenn man versucht von einem leeren Stapel zu ziehen. Sonst Umsetzung sehr gut
